if Meteor.isServer
  Meteor.startup ()->
    Moments._ensureIndex({currentPostId:1, readPostId:1})
    Moments._ensureIndex({currentPostId:1, createdAt: -1})
    Viewers._ensureIndex({userId: 1, createdAt: -1})
    # {postId: 1, userId: 1, createdAt: -1} will create 3 indexs,
    # {postId: 1},{postId: 1,userId: 1},{postId: 1, userId: 1, createdAt: -1}
    #Viewers._ensureIndex({postId: 1})
    #Viewers._ensureIndex({postId: 1,userId: 1})
    Viewers._ensureIndex({postId: 1, userId: 1, createdAt: -1})
    Viewers._ensureIndex({postId: 1, createdAt: -1})
    Follower._ensureIndex({userId: 1, followerId: 1, createAt:-1})
    Follower._ensureIndex({followerId: 1, createAt:-1})
    Follower._ensureIndex({userId: 1, createAt:-1})
    Follows._ensureIndex({index: 1})
    TopicPosts._ensureIndex({postId: 1})
    ReComment._ensureIndex({postId: 1, commentUserId: 1})
    ReComment._ensureIndex({postId: 1})
    Meets._ensureIndex({me: 1, count: -1, createdAt: -1})
    Meets._ensureIndex({me: 1, createdAt: -1})
    #This one need to be deleted in mongodb.
    #Meets._ensureIndex({me: 1, ta: 1, meetOnPostId: 1, count: -1, createdAt: -1})
    Meets._ensureIndex({me: 1, ta: 1})
    Meets._ensureIndex({me: 1, meetOnPostId: 1, createdAt: -1})
    Posts._ensureIndex({owner: 1, createdAt: -1})
    Posts._ensureIndex({createdAt: -1})
    FollowPosts._ensureIndex({followby: 1, createdAt: -1})
    SavedDrafts._ensureIndex({owner: 1, createdAt: -1})
    Feeds._ensureIndex({followby: 1, createdAt: -1})
    Feeds._ensureIndex({followby: 1, postId: 1, eventType: 1, recommanderId: 1, createdAt: -1})
    Comment._ensureIndex({postId: 1})
    Reports._ensureIndex({postId: 1})
    Messages._ensureIndex({userId: 1, toGroupId: 1, "toUsers.userId": 1, toGroupId: 1, createTime: -1})
    Messages._ensureIndex({userId: 1, toUserId: 1, userId: 1, toUserId: 1, createTime: -1})
    MsgSession._ensureIndex({userId: 1, updateTime: -1})
    MsgGroup._ensureIndex({"users.userId": 1})
    Feeds._ensureIndex({recommanderId: 1, recommander: 1, postId: 1, followby: 1})
    Feeds._ensureIndex({requesteeId: 1, requesterId: 1, followby: 1})
    Feeds._ensureIndex({owner:1,followby: 1, checked: 1, postId: 1, pindex: 1})
    PComments._ensureIndex({postId:1,commentUserId:1})
    PComments._ensureIndex({ptype:1})
    # this one do not need index
    # Topics.find({})
    # Topics._ensureIndex({text: 1, createdAt: -1})
    #RefComments._ensureIndex({text: 1})
