
@withSocialBar = false
@withAfterPostIntroduce = false
@withChat = false
@withDiscover = true
@withAutoSavedOnPaused = true
@withPostSuggestionToUser = false
@withNewLayoutMoment = false
@withMusicSharing = true
@withSectionMenu = false
@withSectionShare = false
@withPostTTS = false
@withWeChatSignatureServer = false
@withLocalBase64 = true
@withSuggestAlreadyRead = true
@withSponserLinkAds = false
@isUSVersion = false
@withZhiFaCDN = false
@withServerImport = true
@withShareStoryGroup = false
@withDirectDraftShow = true
@withMobileBackendUploading = false
@withStaticPosts = false
@withNewFilePath=true
@withLanguageSetting=false
@withImportToEdit=false
@signUpUserNameLength = 16
@withPostTitleMaxLength = 180      #byte
@withPostSubTitleMaxLength = 120   #byte
@withShowGroupsUserMaxCount = 10
@withThumbInTextSection = false
@withUserInfoShowInPostHeader = false
@withInlineComment = false
@withInPostMassInformation = false
@withSetTopicAndShareAfterPost = false
@withThirdPartSocialSharing = false
@withFirstScreenTip = false
@withReadMoreButtonOnPost = false
@withEnableHaveReadMsg = false #已读消息
@withSwitchNormalLabelMsg = true
@MQTT_TIME_DIFF = 0
@withAccuracyFuzzinesssInTimeLine = true
@hideLableButtonWithNormalGroupUser = true # 群： 普通成员不显示 标记 相关按钮
@withFollowFeature = true