
@withSocialBar = true
@withAfterPostIntroduce = false
@withChat = false
@withDiscover = true
@withAutoSavedOnPaused = false
@withPostSuggestionToUser = false
@withNewLayoutMoment = true
@withMusicSharing = true
@withSectionMenu = true
@withSectionShare = true
@withPostTTS = false
@withWeChatSignatureServer = false #(Meteor.isServer and process.env.ENABLE_WECHAT_SIGN_SERVER) || 0
@withSuggestAlreadyRead = true
@withForcePopupSectionReview = false
@withSponserLinkAds = false
@withServerImport = true
@withSlackReporter = false
@withSkypeWebReporter = true
@withPostTitleMaxLength = 90      #byte
@withPostSubTitleMaxLength = 60   #byte
@signUpUserNameLength = 16
@withShowGroupsUserMaxCount = 10
@withEnableHomeAI = false
@withDefaultAccuracy = 0.85 #默认最低识别准确度
@withNativeMQTTLIB = false
@languageSetup = 'en' # 'en' or 'cn'
@withLiteVersion = true
