
@withSocialBar = true
@withAfterPostIntroduce = false
@withChat = false
@withDiscover = true
@withAutoSavedOnPaused = true
@withPostSuggestionToUser = false
@withNewLayoutMoment = true
@withMusicSharing = true
@withSectionMenu = true
@withSectionShare = true
@withPostTTS = false
@withWeChatSignatureServer = false
@withLocalBase64 = true
@withSuggestAlreadyRead = true
@withSponserLinkAds = false
@isUSVersion = false
@withZhiFaCDN = false
@withServerImport = true
@withShareStoryGroup = false
@withDirectDraftShow = true
@withMobileBackendUploading = false
@withStaticPosts = false
@withNewFilePath=true
@withLanguageSetting=false
@withImportToEdit=false
@signUpUserNameLength = 16
@withPostTitleMaxLength = 180      #byte
@withPostSubTitleMaxLength = 120   #byte